dist: trusty
sudo: true
install:
    - sudo add-apt-repository -y ppa:cassou/emacs
    - sudo apt-get -qq update
    - sudo apt-get -qq -f install
    - sudo apt-get install emacs24 emacs24-el
script:
    - ./run_tests.sh
